# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qq',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='qq',
        ),
    ]
