# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160425_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsuser',
            name='is_staff',
        ),
    ]
