# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_bsuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
