# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_bsuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='bsuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
